language: node_js
node_js:
  - 0.12
before_install:
  - npm install -g bower grunt-cli codeclimate-test-reporter
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - bower install
  - npm install
script:
  - grunt travis
after_script:
  - codeclimate-test-reporter < test/coverage/**/lcov.info
addons:
  code_climate:
    repo_token: 95be8053813e83f4e7fb8ed21a0d34484498bbf1f2beee9a3a28eef002c87331